// <auto-generated />
using System;
using FarmaciaDigital.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FarmaciaDigital.Migrations
{
    [DbContext(typeof(FarmaciaContext))]
    partial class FarmaciaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmaciaDigital.Models.Adesao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal?>("MensalidadeEfetiva")
                        .HasColumnType("NUMBER(10,2)");

                    b.Property<string>("Observacao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Adesoes");
                });

            modelBuilder.Entity("FarmaciaDigital.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("FilialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.HasKey("Id");

                    b.HasIndex("FilialId");

                    b.ToTable("Clientes");

                    b.HasDiscriminator<string>("TipoCliente").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FarmaciaDigital.Models.Filial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Filiais");
                });

            modelBuilder.Entity("FarmaciaDigital.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<string>("TipoProduto").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FarmaciaDigital.Models.PessoaFisica", b =>
                {
                    b.HasBaseType("FarmaciaDigital.Models.Cliente");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"Cpf\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("FarmaciaDigital.Models.PessoaJuridica", b =>
                {
                    b.HasBaseType("FarmaciaDigital.Models.Cliente");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("\"Cnpj\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("FarmaciaDigital.Models.PlanoSaude", b =>
                {
                    b.HasBaseType("FarmaciaDigital.Models.Produto");

                    b.Property<string>("Cobertura")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("MensalidadeBase")
                        .HasColumnType("NUMBER(10,2)");

                    b.HasDiscriminator().HasValue("PLANO_SAUDE");
                });

            modelBuilder.Entity("FarmaciaDigital.Models.Adesao", b =>
                {
                    b.HasOne("FarmaciaDigital.Models.Cliente", "Cliente")
                        .WithMany("Adesoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmaciaDigital.Models.Produto", "Produto")
                        .WithMany("Adesoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("FarmaciaDigital.Models.Cliente", b =>
                {
                    b.HasOne("FarmaciaDigital.Models.Filial", "Filial")
                        .WithMany("Clientes")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("FarmaciaDigital.Models.Cliente", b =>
                {
                    b.Navigation("Adesoes");
                });

            modelBuilder.Entity("FarmaciaDigital.Models.Filial", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("FarmaciaDigital.Models.Produto", b =>
                {
                    b.Navigation("Adesoes");
                });
#pragma warning restore 612, 618
        }
    }
}
